version: '3.8'

services:
  product-service:
    build: ./assignment1-product-service
    ports:
      - "6767:6767"
    networks:
      - app-network

  order-service:
    build: ./assignment1-order-service
    ports:
      - "7676:7676"
    environment:
      - SERVER_PRODUCT_URL=http://product-service:6767
    depends_on:
      - product-service
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
